### ISSUE TITLE
tranlate3d， 导致字体模糊

### ISSUE THREAD

**Issue by DaskV** [kinglisky/vtip#3]
用translate3d 定位，考虑到不规整的x ,y 位置 导致字体模糊的问题吗？

**Comment by kinglisky** [comment]
translate3d 是会造成这一类的问题，准备写个新版的~

**Comment by EasonYou** [comment]
这个问题可以通过样式去调整吗

**Comment by kinglisky** [comment]
@EasonYou 看看这两个工具能不能满足你的需求，最近没啥时间修坑，鸽了~
![](https://i.loli.net/2019/04/15/5cb4278de0d65.jpg)

https://github.com/Akryum/v-tooltip
https://github.com/KABBOUCHI/vue-tippy

**Comment by EasonYou** [comment]
@kinglisky 
已经在生产环境用上了
现在把will-change去掉并且把translate3d改为translate就可以了，给你提个pr？
还是说这样有问题？
