### ISSUE TITLE
绑定指令的文字换行,提示框会显示在中间

### ISSUE THREAD

**Issue by nanachiOwQ** [kinglisky/vtip#4]
target是一个a标签.但是他比较长.换行了,然后提示框就出现在中间了

提示框模糊的问题能不能把translate3d的值parseInt来解决呢..

**Comment by kinglisky** [comment]
@dracarys26 
这个 tip 工具准备用 `popper.js` 重写，之前位置计算都是手动算的，不是很理想。
推荐个工具 https://github.com/KABBOUCHI/vue-tippy 这个感觉还行。

**Comment by nanachiOwQ** [comment]
@kinglisky 多谢!
